name: Nim CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-latest:
    runs-on: ubuntu-latest
    container:
      image: nimlang/nim
    steps:
    - uses: actions/checkout@v2
    - name: install liburing
      run: sudo apt update && sudo apt install liburing-dev -y
    - name: Update nimble
      run: nimble update
    - name: Run tests
      run: nimble test